arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/l10n/generated
nullable-getter: false  # Ensures non-nullable return types
required-resources: true # Requires all keys in all languages
untranslated-messages-file: lib/l10n/untranslated.json
synthetic-package: false