name: health_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Corrected Dart SDK version for null safety

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.7
  http: ^1.2.1
  flutter_gen: ^5.4.0
  intl_utils: ^2.8.11
  image_picker: ^1.0.4
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.5

  # Firebase dependencies (make sure the versions are compatible)
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  firebase_dynamic_links: ^6.1.10
  google_sign_in: ^6.1.0
  csv: ^6.0.0
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.8
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/landing.jpg
    - assets/images/logo.jpg
    - assets/images/on_board_1.avif
    - assets/images/on_board_2.jpg
    - assets/images/on_board_3.jpg
    - assets/images/login.jpg
    - assets/images/a.jpg
    - assets/images/b.jpg
    - assets/images/c.png
    - assets/images/p1.jpg
    - assets/images/p2.jpg
    - assets/images/p3.jpg
    - assets/images/p4.jpg
    - assets/images/ab1.jpg
    - assets/images/ab2.png
    - assets/images/ab3.png
    - assets/images/Google.png
    - assets/Health.csv

  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSansSinhala-Regular.ttf
        - asset: fonts/NotoSansTamil-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "android/app/src/main/icon.png"
  min_sdk_android: 21
